# Usa la imagen oficial de Python
FROM python:3.9-alpine

# Copia el código fuente al contenedor
COPY main.py /main.py

# Define el directorio de trabajo
WORKDIR /app

# Ejecuta el script de Python
CMD ["python", "/main.py"]
 
